graph TB
  main["main.cpp"]
  WakeUPH["WakeUP.hpp"]
  WakeUPC["WakeUP.cpp"]
  main -- "Includes" --> WakeUPH
  WakeUPH -- "Implemented in" --> WakeUPC
  linkStyle 0 stroke:#2ecd71,stroke-width:2px;
  linkStyle 1 stroke:#2ecd71,stroke-width:2px;
