version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  nodejs:
    build: ../Image
    volumes:
      - ../Image:/app
      - /app/node_modules
    ports:
      - 8081:8081
    depends_on:
      - mongodb
volumes:
  mongodb_data: